const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "Symple Login System",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "https://login-system-trabalhadores.herokuapp.com",
  basePath: "/",
  schemes: ["https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "User CRUD related endpoints",
    },
    {
      name: "Auth",
      description: "Authorization related endpoints",
    },
  ],
  definitions: {
    User: {
      username: "jhondoe",
      email: "jhondoe@email.com",
      password: "ultrasecretpassword",
      id: "generated-id-from-uuidv4-lib",
      last_login: "2022-01-01",
      createdAt: "2022-01-01",
      updatedAt: "2022-01-01",
    },
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./src/controllers/user/index.js","./src/controllers/auth/index.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./index"); // Your project's root file
});
